services:
  emulator:
    build: .
    container_name: android-emulator-docker
    # volumes:
    #   - .:/home/ubuntu/emulator
    ports:
      - "8000:80"
      # - "5554:5554"
      # - "5555:5555"
    command: sleep infinity
